### ISSUE TITLE
"More" menu is hidden on "Scheduled Jobs" screen

### ISSUE THREAD

**Issue by MegaphoneJon** [civicrm/org.civicrm.shoreditch#457] opened 2020-07-10 15:36 UTC
This is with the master branch - if you visit **Administer menu » System Settings » Scheduled Jobs**, the **More** menu next to each job is missing, preventing use of "Execute Now" and similar.

**Comment by MegaphoneJon** [comment] 2020-07-10 19:18
The "More" menu is actually hidden on a lot of pages, like "Manage Groups".  I'm running Shoreditch b1, Civi 5.27.1, with the Shoreditch CiviAdmin Companion Drupal theme 1.0 .

**Comment by MegaphoneJon** [comment] 2020-07-16 21:27
I did a `git bisect` and traced it back to https://github.com/civicrm/civicrm-core/pull/17295.

**Comment by jmcclelland** [comment] 2020-07-28 15:41
I'm seeing the same behavior.

**Comment by MegaphoneJon** [comment] 2020-07-28 19:52
@jmcclelland I haven't had a chance to test - but it looks like #461 might be a solution?

**Comment by jmcclelland** [comment] 2020-07-28 20:41
It only took me an hour to get gulp to work properly... but no, that didn't solve it for me. 

But I may not be doing it right.

After I apply those changes, the css attributes it removes, remain with the same settings. When I mess with those attributes in inspector I can get the more link to show on the groups page.

I think it's closely related to #461 but how this is handled on the event and contribution pages is different then how it's handled on the manage group (and scheduled jobs)

**Comment by MegaphoneJon** [comment] 2020-07-28 21:02
@jmcclelland One of my staff worked on this last week, I thought #461 was a better solution if it worked - but since it didn't, here's a change to core.  I'm not sure if it's been tested on non-Shoreditch installs - been meaning to test it myself but haven't had a moment:

```diff
diff --git a/sites/all/modules/civicrm/css/civicrm.css b/sites/all/modules/civicrm/css/civicrm.css
index d260ee66..e0a4bdc6 100644
--- a/sites/all/modules/civicrm/css/civicrm.css
+++ b/sites/all/modules/civicrm/css/civicrm.css
@@ -1555,6 +1555,7 @@ input.crm-form-entityref {
   font-family: "FontAwesome";
   content: "\f0da";
   padding-left: .5ex;
+  display: block;
 }
 
 .crm-container .btn-slide-active .panel {
```

**Comment by jmcclelland** [comment] 2020-07-28 21:09
Thanks @MegaphoneJon - that fix does work for me. I don't fully understand what's going on with all the css (I see the "..." button, but not "more" and not the nice font awesome triangle promited in the git commit you found). But at least it is functional!

**Comment by jmcclelland** [comment] 2020-07-28 21:14
![contribution-pages-misaligned](https://user-images.githubusercontent.com/4511942/88722737-bfb38680-d0f5-11ea-92bf-0e3f01df5483.png)

Well... we're still on team functional! But this change makes the event and contribution page links get mis-aligned.

**Comment by agh1** [comment] 2020-07-31 20:47
Please forgive any ignorance you find in this post because I'm not a Shoreditch user personally.  However, it seems to me that the problem is this:
https://github.com/civicrm/org.civicrm.shoreditch/blob/9d71e2974d1db00f0c08f42bfac6cab9d9f78c19/scss/civicrm/common/_base.scss#L118-L123

The text of the "more" is yanked off the screen for whatever reason, presumably because someone didn't like it.  The `.crm-container span.btn-slide::after` had been set to display as a block because it was displaying an image.  Now, it displays inline because it's text (like all font icons).  I think #461 is basically trying to undo this.

The snippet above from @MegaphoneJon will make Shoreditch work, but it may cause problems with alignment for the rest of us.  One solution might be to simply update the Shoreditch CSS to make that display as a block here:
https://github.com/civicrm/org.civicrm.shoreditch/blob/9d71e2974d1db00f0c08f42bfac6cab9d9f78c19/scss/civicrm/common/_base.scss#L125

Ultimately, the "more" comes from what's passed to `CRM_Core_Action::formLink()`, and I would suggest that what text appears there is potentially quite important.  Many core developers will have no idea it will be hidden by Shoreditch, and I suspect many reviewers won't think twice about that, either.  Consequently, it's a bit risky for Shoreditch to ditch the "more".  I don't know what the limitations of #461 are, but I'd suggest it's the right direction.

**Comment by larssg-wildsight** [comment] 2020-08-07 19:33
Sorry for the duplicate issue. I'm also seeing that the more menu for contribution pages (which is present) is missing the disable and delete options. Seems like a different issue to me, but I thought I would check that with folks here before making a new issue.

**Comment by jitendrapurohit** [comment] 2020-08-13 10:57
Have noticed the same problem. Fixed by adding a custom css filename ion the ResourceURL page. 

    /* Fixes hidden/missing buttons on contribution page r21499 */
    .crm-container span.btn-slide.crm-hover-button {
        text-indent: 0;
        padding-right: 1em;
        width: fit-content;
    }

It seems to re-iterate the first option, so not perfect, but better than not displaying the dots :)

![image](https://user-images.githubusercontent.com/5929648/90126793-d6a6d980-dd81-11ea-91ce-6d08dba01758.png)

**Comment by jmcclelland** [comment] 2020-08-13 21:51
@jitendrapurohit's css is definitely better then `display: block`, but it didn't work on the Manage Groups page. Here's my variation:

```
.crm-container span.btn-slide.crm-hover-button {      
      text-indent: 0 !important;                        
      padding-right: 1em !important;                    
      width: auto !important;                 
  }  
```

**Comment by edvanleeuwen** [comment] 2020-09-01 09:13
Related https://lab.civicrm.org/extensions/dataprocessor/-/issues/49.

**Comment by jamienovick** [comment] 2020-09-01 10:35
Hi all,

Just to mention that we are working on a new release of Shoreditch that will include a fix to this issue. Sorry it's taken a bit of time as we're working to test the entire Shoreditch extension at the same time.

@swastikpareek @rebecca-compucorp

Thanks

J

**Comment by thomst** [comment] 2020-09-03 10:02
@jamienovick:
Thank you for working on the fix.
We recently updated the CiviCRM-installations of most of our customers. About 50 customers are affected by this issue. Could you approximately say when you will release the fixed version. It would help us with our customer communication. Thanks a lot.

**Comment by ivan-compucorp** [comment] 2020-09-03 14:04
Created a [PR](https://github.com/civicrm/org.civicrm.shoreditch/pull/469) to fix this issue.

**Comment by marcelocompucorp** [comment] 2020-09-08 15:44
Hi all,

A new Shoreditch version with a fix for this issue has just been released: https://github.com/civicrm/org.civicrm.shoreditch/releases/tag/1.0.0-beta.2

Cheers,

**Comment by reneolivo** [comment] 2020-09-08 16:10
Closing this issue since it has been fixed by  https://github.com/civicrm/org.civicrm.shoreditch/pull/469 which has also been released.

**Closed by reneolivo** 2020-09-08 16:10 UTC
